### PR TITLE
Specify CMS branch using env config

### PR DESCRIPTION
**Pull request by dhruvparekh12**
Many a times, users try to deploy the contentstack-nextjs-starter-app on Launch using a delivery token scoped to a Contentstack branch, other than the default main branch. But, the deployments fail with this error
```
Error: {"error_message":"Access denied. You have insufficient permissions to perform operation on this branch 'main'.","error_code":901}
```

To fix this, users need to be able to optionally set an environment variable `CONTENTSTACK_BRANCH` mentioning the name of the branch on Contentstack. 
Code changes in this PR will allow users to set `CONTENTSTACK_BRANCH` environment variable so their deployments can be successful on Launch.

### CODE REVIEW

**Comment by dhruvparekh12** [comment]
Hi @Amitkanswal @surajcontentstack @abhishek305 
Can you please review and approve these changes?

**Review by surajcontentstack — APPROVED** [review]

**Comment by abhishek305** [comment]
Hi @dhruvparekh12,
Could you please add a description/changes made giving context?

**Note: Changed the base branch to staging**

cc @Amitkanswal @surajcontentstack

**Comment by dhruvparekh12** [comment]
Hi @abhishek305 

Added description. Please let me know if any additional information is required.

**Review by Amitkanswal — APPROVED** [review]

**Comment by dhruvparekh12** [comment]
Hi team,
Can we merge this?
I do not have permission to merge, can you please complete the merge on this PR?
Thanks

**Review by systemsconsciousness — COMMENTED** [review]
Testing this change, and it is working. -DH

**Pull request merged**
